name: toolchain image (evk49)

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Check out the toolchain repo
      uses: actions/checkout@v3
      with:
        repository: nu120/toolchain_arm_gcc-linaro-6.3.1
        path: toolchain
        token: ${{ secrets.gh_token }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.ghcr_username }}
        password: ${{ secrets.gh_token }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ghcr.io/nu120/buildroot:toolchain_evk49
